//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage()
        {
            this.StorageSelections = new HashSet<StorageSelection>();
        }
    
        public int StorageId { get; set; }
        public int FacilityId { get; set; }
        public int StorageTypeId { get; set; }
        public bool Activation { get; set; }
        public Nullable<int> MemberId { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual StorageType StorageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorageSelection> StorageSelections { get; set; }
    }
}
