//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageSelection
    {
        public int StorageSelectionId { get; set; }
        public int StorageId { get; set; }
        public int FeeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int ReceiptId { get; set; }
        public System.DateTime ExitDateExpected { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
    
        public virtual Fee Fee { get; set; }
        public virtual Reciept Reciept { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
